name: Testing wf variables

on:
 workflow_dispatch

env: 
  cloud: google-cloud

jobs:
  greeting_job:
    runs_on: ubuntu-latest
    env:
      greeting: hello

    steps:
      - name: "Say Hello"
        run: echo "$greeting $first_name is using %cloud"
        env:
          first_name: Haridas
