name: Testing wf variables

on:
 workflow_dispatch

env: 
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: test
    env:
      greeting: hello

    steps:
      - name: "Say Hello"
        run: echo "$greeting $first_name is using $cloud with project ${{ vars.PROJECT_TD }}"
        env:
          first_name: Haridas
