name: Testing wf variables

on:
 workflow_dispatch

env: 
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: test
    env:
      greeting: hello
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: "Say Hello"
        run: echo "$greeting $first_name is using $cloud with project ${{ vars.PROJECT_TD }} sub_project ${{ vars.SUB_PROJECT }} !!!"
        env:
          first_name: Haridas
      - name: "Checking context variables"
        run: |
          echo "Repository Name: ${{ github.Repository }}"
          echo "Workflow Name: ${{ github.Workflow }}"
          echo "Triggered By: ${{ github.triggering_actor }}"
      - name: "checking Secrets"
        run: |
          echo "secret_value: ${{Secrets.MY_TEST}}"
